version: 2
jobs:
  build:
    working_directory: ~/pk-api
    docker:
      - image: circleci/node:8.7.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install node modules
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  test:
    working_directory: ~/pk-api
    docker:
      - image: circleci/node:8.7.0
    steps:
      - checkout
      - run:
          name: Run tests
          command: echo "No tests for now"

  deployment:
    working_directory: ~/pk-api
    machine: true
    steps:
      - checkout
      - add_ssh_keys
      - deploy:
          name: Deploy to dokku
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "$server_ip $pub_key" >> ~/.ssh/known_hosts
              cat ~/.ssh/known_hosts
              [[ ! -e "$(git rev-parse --git-dir)/shallow" ]] || git fetch --unshallow
              git remote add dokku dokku@$server_ip:pk-api
              git push dokku master
            fi

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
      - deployment:
          requires:
            - build
            - test
          filters:
            branches:
              only: master

